// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resurgam.Infrastructure.Data;

namespace Resurgam.Infrastructure.Migrations
{
    [DbContext(typeof(ResurgamContext))]
    [Migration("20181013012340_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Resurgam.AppCore.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryId1");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Order");

                    b.Property<Guid?>("ParentCategoryId");

                    b.Property<Guid>("ProjectId");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryId1");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.CategoryTopic", b =>
                {
                    b.Property<Guid>("ProjectId");

                    b.Property<Guid>("ParentCategoryId");

                    b.Property<Guid>("TopicId");

                    b.Property<Guid?>("CategoryId");

                    b.Property<int>("Order");

                    b.HasKey("ProjectId", "ParentCategoryId", "TopicId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("CategoryTopic");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.CollectionElement", b =>
                {
                    b.Property<Guid>("CollectionElementId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("ProjectId");

                    b.Property<Guid>("TopicId");

                    b.HasKey("CollectionElementId");

                    b.HasIndex("TopicId");

                    b.ToTable("CollectionElement");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CustomCssId");

                    b.Property<string>("LogoFileName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("LogoFileName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ProjectId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("ProjectId");

                    b.Property<Guid?>("TopicId");

                    b.HasKey("TagId");

                    b.HasIndex("TopicId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.Topic", b =>
                {
                    b.Property<Guid>("TopicId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CollectionElementId");

                    b.Property<Guid?>("DefaultCategoryId");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("DocumentName");

                    b.Property<Guid?>("FileResourceId");

                    b.Property<Guid?>("ImageResourceId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("ProjectId");

                    b.Property<string>("TopicContent");

                    b.Property<int>("TopicTypeId");

                    b.HasKey("TopicId");

                    b.HasIndex("CollectionElementId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.Category", b =>
                {
                    b.HasOne("Resurgam.AppCore.Entities.Category")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId1");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.CategoryTopic", b =>
                {
                    b.HasOne("Resurgam.AppCore.Entities.Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Resurgam.AppCore.Entities.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.CollectionElement", b =>
                {
                    b.HasOne("Resurgam.AppCore.Entities.Topic", "Topic")
                        .WithMany("CollectionElements")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.Project", b =>
                {
                    b.HasOne("Resurgam.AppCore.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.Tag", b =>
                {
                    b.HasOne("Resurgam.AppCore.Entities.Topic")
                        .WithMany("Tags")
                        .HasForeignKey("TopicId");
                });

            modelBuilder.Entity("Resurgam.AppCore.Entities.Topic", b =>
                {
                    b.HasOne("Resurgam.AppCore.Entities.CollectionElement")
                        .WithMany("ElementTopics")
                        .HasForeignKey("CollectionElementId");
                });
#pragma warning restore 612, 618
        }
    }
}
